version: '3.7'
services:
  squash-tm-pg:
    container_name: squash-tm-pg     
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres:9.6.12
    volumes:
      - "/var/lib/db-postgresql:/var/lib/postgresql/data" 
  
  squash-tm:
    depends_on:
      - squash-tm-pg
    environment:
      POSTGRES_ENV_POSTGRES_USER: ${DB_USER}
      POSTGRES_ENV_POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ENV_POSTGRES_DB: ${DB_DATABASE}  
    ports:
      - 8090:8080/tcp
    image: squashtest/squash-tm:1.19.3
    links:
      - squash-tm-pg:postgres
    volumes:
      - squash-tm-logs:/opt/squash-tm/logs
      - squash-tm-plugins:/opt/squash-tm/plugins  
  
volumes:
  squash-tm-logs:
  squash-tm-plugins:
